name: CI

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        zig-version: [0.14.1]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
      - name: Run build
        run: zig build
        working-directory: ./example